#! /usr/bin/env python3

import sys

FILE_HEADER = '''#pragma once
//This File is autogenerated an may be overriden, do not change
//If you need to change the content of the file please change the file
//sources/message_hdr.py'''


prefix = sys.argv[1] + '/'
with open(sys.argv[2], 'w') as output:
  output.write(f"{FILE_HEADER}\n")
  for i in range(3, len(sys.argv)):
    for include in sys.argv[i].split(';'):
      include = include.removeprefix(prefix)
      output.write(f"#include <{include}>\n")